name: 3. Trigger Jenkins Webhook

on:
  workflow_call:

jobs:
  webhook:
    # 이미지 빌드 워크플로우가 성공한 경우에만 실행
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      # 1. 커밋 메시지 표시
      - name: Display Commit Message
        run: |
          echo "Commit Message: ${{ github.event.workflow_run.head_commit.message }}"

      # 2. Jenkins로 웹훅 전달
      - name: Trigger Multibranch Scan via Webhook
        run: |
          set -e
          set +x
          
          curl --fail -S -X POST \
            "${{ secrets.JENKINS_URL }}/multibranch-webhook-trigger/invoke?token=${{ secrets.JENKINS_AUTH_TOKEN }}"
          
          echo "✅ Jenkins Multibranch scan triggered successfully using webhook token."