name: 3. Trigger Jenkins Webhook

# 이미지 빌드 워크플로우가 성공적으로 완료되면 실행
on:
  workflow_run:
    workflows: ["2. Build Docker Image"]
    types:
      - completed
    branches:
      - main

jobs:
  webhook:
    # 이미지 빌드 워크플로우가 성공한 경우에만 실행
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      # 1. 커밋 메시지 표시
      - name: Display Commit Message
        run: |
          echo "Commit Message: ${{ github.event.workflow_run.head_commit.message }}"

      # 2. Jenkins로 웹훅 전달
      - name: Trigger Jenkins Build with Crumb
        run: |
          set +x
          CRUMB=$(curl -s --user "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_API_TOKEN }}" \
            "${{ secrets.JENKINS_URL }}/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,\":\",//crumb)")

          curl -X POST "${{ secrets.JENKINS_URL }}/job/practice/buildWithParameters?token=${{ secrets.JENKINS_AUTH_TOKEN }}" \
            --user "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_API_TOKEN }}" \
            -H "$CRUMB"